"""
Kaggle Job Postings → Role Skills Frequency Table

Dataset: LinkedIn Job Postings
URL: https://www.kaggle.com/datasets/arshkon/linkedin-job-postings

Setup:
    pip install kaggle pandas
    kaggle datasets download -d arshkon/linkedin-job-postings
    unzip linkedin-job-postings.zip -d linkedin-job-postings

Then run:
    python kaggle_extract.py

This overwrites the ROLE_SKILLS_FREQ table in role_skills.py with real data.
"""

import pandas as pd
import json
import re
from collections import defaultdict

# ── Config ───────────────────────────────────────────────
POSTINGS_CSV = "linkedin-job-postings/postings.csv"
TOP_ROLES = [
    "product manager", "software engineer", "data analyst",
    "data scientist", "engineering manager", "ux designer",
    "marketing manager", "project manager", "business analyst", "devops engineer"
]
MIN_POSTINGS = 30
TOP_SKILLS_PER_ROLE = 12

SKILL_KEYWORDS = [
    "Python", "SQL", "JavaScript", "TypeScript", "React", "Node.js",
    "AWS", "Docker", "Kubernetes", "Git", "CI/CD", "Terraform",
    "Agile", "Scrum", "JIRA", "Confluence", "Figma", "Sketch",
    "Tableau", "Power BI", "Excel", "TensorFlow", "PyTorch",
    "Machine Learning", "Deep Learning", "NLP", "Statistics",
    "Stakeholder Management", "Product Roadmapping", "A/B Testing",
    "User Research", "Data Analysis", "Data Visualization",
    "SEO", "Google Analytics", "HubSpot", "Salesforce",
    "Leadership", "Communication", "OKRs", "Hiring",
    "System Design", "REST APIs", "Microservices", "Linux", "Bash",
    "Product Strategy", "Competitive Analysis", "Wireframing",
    "Usability Testing", "Design Systems", "Adobe XD",
]

def normalize_role(title: str) -> str:
    if not isinstance(title, str):
        return None
    t = title.lower().strip()
    for role in TOP_ROLES:
        if role in t:
            return role
    return None

def extract_skills(text: str) -> list[str]:
    if not isinstance(text, str):
        return []
    found = []
    for skill in SKILL_KEYWORDS:
        # Word boundary match to avoid "R" matching inside "requirements"
        pattern = r'\b' + re.escape(skill) + r'\b'
        if re.search(pattern, text, re.IGNORECASE):
            found.append(skill)
    return list(set(found))  # deduplicate per posting

def main():
    print("Loading postings.csv...")
    df = pd.read_csv(POSTINGS_CSV, usecols=["title", "description", "skills_desc"], low_memory=False)
    print(f"Loaded {len(df)} postings")

    df["role"] = df["title"].apply(normalize_role)
    df = df[df["role"].notna()]
    print(f"Matched {len(df)} postings to known roles")

    role_skill_counts = defaultdict(lambda: defaultdict(int))
    role_totals = defaultdict(int)

    for _, row in df.iterrows():
        role = row["role"]
        # Prefer skills_desc, fall back to description
        text = str(row["skills_desc"]) if pd.notna(row["skills_desc"]) else str(row["description"])
        skills = extract_skills(text)
        role_totals[role] += 1
        for skill in skills:
            role_skill_counts[role][skill] += 1

    freq_table = {}
    for role, skill_counts in role_skill_counts.items():
        total = role_totals[role]
        if total < MIN_POSTINGS:
            print(f"  Skipping {role} — only {total} postings")
            continue
        freqs = {skill: round(count / total, 2) for skill, count in skill_counts.items()}
        top = dict(sorted(freqs.items(), key=lambda x: x[1], reverse=True)[:TOP_SKILLS_PER_ROLE])
        freq_table[role] = top
        print(f"  {role}: {total} postings → top skill: {list(top.keys())[0]} ({list(top.values())[0]*100:.0f}%)")

    # Read existing file to preserve helper functions
    with open("role_skills.py", "r") as f:
        original = f.read()

    match = re.search(r'\n\ndef get_role_skills', original)
    helpers = original[match.start():] if match else ""

    output = f'''"""
Role-to-skills frequency table.
AUTO-GENERATED by kaggle_extract.py — do not edit manually.
Source: LinkedIn Job Postings (Kaggle), {len(df)} postings analyzed.
"""

ROLE_SKILLS_FREQ = {json.dumps(freq_table, indent=4)}
''' + helpers

    with open("role_skills.py", "w") as f:
        f.write(output)

    print(f"\nDone. role_skills.py updated with {len(freq_table)} roles.")

if __name__ == "__main__":
    main()
