"""
Role-to-skills frequency table.
AUTO-GENERATED by kaggle_extract.py — do not edit manually.
Source: LinkedIn Job Postings (Kaggle), 6001 postings analyzed.
"""

ROLE_SKILLS_FREQ = {
    "marketing manager": {
        "Communication": 0.65,
        "Leadership": 0.39,
        "SEO": 0.17,
        "Excel": 0.17,
        "Hiring": 0.15,
        "Salesforce": 0.1,
        "Google Analytics": 0.09,
        "Data Analysis": 0.07,
        "HubSpot": 0.06,
        "Competitive Analysis": 0.05,
        "A/B Testing": 0.04,
        "Product Strategy": 0.03
    },
    "software engineer": {
        "Agile": 0.41,
        "Python": 0.39,
        "Communication": 0.37,
        "SQL": 0.32,
        "AWS": 0.3,
        "JavaScript": 0.28,
        "Hiring": 0.2,
        "Kubernetes": 0.19,
        "Docker": 0.18,
        "Leadership": 0.18,
        "React": 0.18,
        "Git": 0.16
    },
    "project manager": {
        "Communication": 0.66,
        "Leadership": 0.41,
        "Excel": 0.21,
        "Hiring": 0.15,
        "Agile": 0.15,
        "Scrum": 0.07,
        "JIRA": 0.07,
        "Stakeholder Management": 0.03,
        "Salesforce": 0.02,
        "Confluence": 0.02,
        "Statistics": 0.01,
        "SQL": 0.01
    },
    "engineering manager": {
        "Leadership": 0.57,
        "Communication": 0.47,
        "Hiring": 0.23,
        "Agile": 0.12,
        "AWS": 0.08,
        "Excel": 0.08,
        "Python": 0.07,
        "React": 0.04,
        "Docker": 0.04,
        "SQL": 0.04,
        "Salesforce": 0.04,
        "Machine Learning": 0.03
    },
    "business analyst": {
        "Communication": 0.56,
        "Agile": 0.34,
        "Excel": 0.28,
        "SQL": 0.24,
        "Leadership": 0.19,
        "Data Analysis": 0.17,
        "JIRA": 0.15,
        "Hiring": 0.13,
        "Scrum": 0.11,
        "Confluence": 0.07,
        "Tableau": 0.07,
        "Power BI": 0.06
    },
    "data analyst": {
        "SQL": 0.61,
        "Communication": 0.38,
        "Data Analysis": 0.36,
        "Excel": 0.36,
        "Python": 0.34,
        "Statistics": 0.21,
        "Tableau": 0.21,
        "Leadership": 0.2,
        "Data Visualization": 0.17,
        "Hiring": 0.16,
        "Power BI": 0.15,
        "Agile": 0.14
    },
    "devops engineer": {
        "CI/CD": 0.57,
        "AWS": 0.5,
        "Python": 0.49,
        "Kubernetes": 0.48,
        "Docker": 0.45,
        "Terraform": 0.42,
        "Communication": 0.38,
        "Linux": 0.33,
        "Agile": 0.26,
        "Git": 0.23,
        "Bash": 0.18,
        "SQL": 0.14
    },
    "product manager": {
        "Communication": 0.63,
        "Agile": 0.41,
        "Leadership": 0.39,
        "Hiring": 0.3,
        "Product Strategy": 0.26,
        "Scrum": 0.19,
        "Excel": 0.12,
        "JIRA": 0.1,
        "Data Analysis": 0.09,
        "SQL": 0.09,
        "Machine Learning": 0.06,
        "Competitive Analysis": 0.06
    },
    "data scientist": {
        "Python": 0.85,
        "Machine Learning": 0.71,
        "Statistics": 0.62,
        "SQL": 0.59,
        "Communication": 0.48,
        "Data Analysis": 0.38,
        "AWS": 0.24,
        "Deep Learning": 0.2,
        "Data Visualization": 0.2,
        "Leadership": 0.19,
        "Tableau": 0.18,
        "Hiring": 0.18
    },
    "ux designer": {
        "Figma": 0.63,
        "Communication": 0.47,
        "Agile": 0.39,
        "Sketch": 0.37,
        "User Research": 0.32,
        "Usability Testing": 0.24,
        "Adobe XD": 0.22,
        "Leadership": 0.2,
        "JavaScript": 0.15,
        "Hiring": 0.15,
        "Scrum": 0.1,
        "Design Systems": 0.1
    }
}


def get_role_skills(target_role: str, top_n: int = 8) -> dict:
    """
    Returns top N skills for a given role with their frequencies.
    Uses fuzzy keyword matching against known roles.
    Falls back to a general tech skill set if no match found.
    """
    role_lower = target_role.lower()

    # Direct keyword match
    for key in ROLE_SKILLS_FREQ:
        if key in role_lower or role_lower in key:
            skills = ROLE_SKILLS_FREQ[key]
            # Return top N by frequency
            return dict(sorted(skills.items(), key=lambda x: x[1], reverse=True)[:top_n])

    # Partial word match
    role_words = set(role_lower.split())
    best_match = None
    best_overlap = 0
    for key in ROLE_SKILLS_FREQ:
        key_words = set(key.split())
        overlap = len(role_words & key_words)
        if overlap > best_overlap:
            best_overlap = overlap
            best_match = key

    if best_match and best_overlap > 0:
        skills = ROLE_SKILLS_FREQ[best_match]
        return dict(sorted(skills.items(), key=lambda x: x[1], reverse=True)[:top_n])

    # Fallback — generic professional skills
    return {
        "Communication": 0.90,
        "Stakeholder Management": 0.80,
        "Data Analysis": 0.70,
        "Project Management": 0.65,
        "Agile/Scrum": 0.60,
        "Excel": 0.55,
        "SQL": 0.50,
        "Python": 0.45,
    }


def get_missing_skills(user_skill_names: list[str], target_role: str, threshold: float = 0.5) -> list[str]:
    """
    Compares user's skills against role frequency table.
    Returns skills that appear in >threshold of job postings but are missing from user profile.
    """
    role_skills = get_role_skills(target_role, top_n=12)
    user_skills_lower = {s.lower() for s in user_skill_names}

    missing = []
    for skill, freq in role_skills.items():
        if freq >= threshold:
            # Check if user has this skill (fuzzy)
            skill_lower = skill.lower()
            has_skill = any(
                skill_lower in u or u in skill_lower
                for u in user_skills_lower
            )
            if not has_skill:
                missing.append(skill)

    return missing
